server:
  servlet:
    contextPath: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clear-solutions
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        check_nullability: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

user:
  age:
    min: 18